USB_VID = 0x239A
USB_PID = 0x80F4
USB_PRODUCT = "Spotpear RP2040 ESP32C3"
USB_MANUFACTURER = "Raspberry Pi"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"

# slim build
CIRCUITPY_PICODVI = 0
CIRCUITPY_USB_HOST = 0
CIRCUITPY_USB_VIDEO = 0
CIRCUITPY_WEB_WORKFLOW = 0
CIRCUITPY_MDNS = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_STATUS_BAR = 0

FROZEN_MPY_DIRS += $(TOP)/frozen/circuitpython-esp32at
