# USB_VID/USB_VID are fake
USB_VID = 0x1C35
USB_PID = 0x0001
USB_PRODUCT = "Elecrow CrowPanel 4.2in E-Ink with ESP32-S3"
USB_MANUFACTURER = "Elecrow"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_SIZE = 8MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_ESPCAMERA = 0
