USB_VID = 0x2E8A
USB_PID = 0x101B
USB_PRODUCT = "Tufty 2040"
USB_MANUFACTURER = "Pimoroni"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"

CIRCUITPY__EVE = 1

# slim build
CIRCUITPY_PICODVI = 0
CIRCUITPY_USB_HOST = 0
CIRCUITPY_USB_VIDEO = 0
CIRCUITPY_WEB_WORKFLOW = 0
CIRCUITPY_MDNS = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_STATUS_BAR = 0
